trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: UseNode@1
      inputs:
        version: '14.x'

    - script: |
        npm install
      displayName: 'Install dependencies'

    - script: |
        tar -czvf nodejs-app.tar.gz app.js package.json
      displayName: 'Package application'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: 'nodejs-app.tar.gz'
        artifactName: 'nodejs-app'
        publishLocation: 'Container'

- stage: DeployDev
  dependsOn: Build
  jobs:
  - deployment: DeployDev
    environment: 'Dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: 'nodejs-app'
              targetPath: '$(Pipeline.Workspace)/nodejs-app'
          
          - script: |
              mkdir -p ~/.ssh
              echo "$SSH_PRIVATE_KEY" | sed 's/_/\n/g' > ~/.ssh/id_rsa
              chmod 600 ~/.ssh/id_rsa
              ssh-keyscan -H ${DEV_SERVER#*@} >> ~/.ssh/known_hosts
              echo "First few lines of id_rsa to verify:"
              head -n 5 ~/.ssh/id_rsa
            displayName: 'Prepare SSH Key'

          - script: |
              ssh -i ~/.ssh/id_rsa $DEV_SERVER sudo yum update -y
              ssh -i ~/.ssh/id_rsa $DEV_SERVER curl -sL https://rpm.nodesource.com/setup_18.x | sudo bash -
              ssh -i ~/.ssh/id_rsa $DEV_SERVER sudo yum install -y nodejs
              ssh -i ~/.ssh/id_rsa $DEV_SERVER node -v
              ssh -i ~/.ssh/id_rsa $DEV_SERVER npm -v
            displayName: 'Install Node.js and npm on EC2'

          - script: |
              scp -i ~/.ssh/id_rsa nodejs-app.tar.gz $DEV_SERVER:/tmp/
              ssh -i ~/.ssh/id_rsa $DEV_SERVER tar -xzvf /tmp/nodejs-app.tar.gz -C /tmp/
              ssh -i ~/.ssh/id_rsa $DEV_SERVER npm install --prefix /tmp
              ssh -i ~/.ssh/id_rsa $DEV_SERVER nohup node /tmp/app.js > /tmp/nodejs-app.log 2>&1 &
            displayName: 'Deploy to Dev server'
